- name: Release
  uses: softprops/action-gh-release@v2
  with:
    files: |
      $(find build/libs -name '*.jar' | grep -v 'sources' | grep -v 'javadoc' | grep -v 'dev' | head -n 1)
  permissions:
    contents: write
  on:
    release:
      types: [created]
      tags: v*